# Generated by Django 3.0.4 on 2021-02-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='title',
        ),
    ]
