# Generated by Django 3.1.6 on 2021-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
