# Generated by Django 3.1.6 on 2021-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210210_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
