# Generated by Django 3.1.6 on 2021-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_announcement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
