# Generated by Django 3.1.6 on 2021-02-26 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210226_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classrooms', to='api.classroom'),
        ),
    ]
