# Generated by Django 3.1.6 on 2021-02-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210226_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='api.userprofile'),
        ),
    ]
