# Generated by Django 3.1.6 on 2021-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210226_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='covers/default.jpg', upload_to='covers')),
            ],
        ),
    ]
