# Generated by Django 3.1.6 on 2021-02-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_cardcovers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardCovers',
            new_name='Covers',
        ),
    ]
