# Generated by Django 3.1.6 on 2021-02-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210227_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covers',
            new_name='Cover',
        ),
    ]
