# Generated by Django 3.1.6 on 2021-03-01 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210228_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cover'),
        ),
    ]
