# Generated by Django 3.1.6 on 2021-03-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_choice_messages_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='api.Choice'),
        ),
    ]
