# Generated by Django 3.1.6 on 2021-05-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_lesson_lessonstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonstep',
            old_name='lesson_name',
            new_name='lesson_title',
        ),
        migrations.RemoveField(
            model_name='lessonstep',
            name='condition',
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='Lesson_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='image1',
            field=models.ImageField(null=True, upload_to='lessons'),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='image2',
            field=models.ImageField(null=True, upload_to='lessons'),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='lesson_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lessonstep',
            name='lesson_number',
            field=models.IntegerField(null=True),
        ),
    ]
