# Generated by Django 3.1.6 on 2021-05-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20210526_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstep',
            name='lesson_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_title', to='api.lesson'),
        ),
    ]
