# Generated by Django 3.1.6 on 2021-05-27 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20210527_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonstep',
            name='image2',
        ),
    ]
