# Generated by Django 3.1.6 on 2021-05-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_gradedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradedtask',
            name='task',
        ),
    ]
