# Generated by Django 3.1.6 on 2021-02-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menu_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='company',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='steps',
            name='menu',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
