# Generated by Django 3.1.6 on 2021-02-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_announcement_author_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author_avatar',
        ),
    ]
