# Generated by Django 3.1.6 on 2021-02-23 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210223_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
