# Generated by Django 3.1.6 on 2021-02-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210225_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='classroom',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='level',
            new_name='level_id',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='school_year',
            new_name='school_year_id',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='classroom',
            new_name='classroom_id',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='student',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
