# Generated by Django 3.1.6 on 2021-02-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210227_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covers',
            name='image',
            field=models.ImageField(default='/covers/default.jpg', upload_to='covers'),
        ),
    ]
