# Generated by Django 3.1.6 on 2021-03-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_posted']},
        ),
    ]
