# Generated by Django 3.1.6 on 2021-03-22 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_board_boardmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessages',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
