# Generated by Django 3.1.6 on 2021-03-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210322_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmessages',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_message', to='api.board'),
        ),
    ]
