# Generated by Django 3.1.6 on 2021-03-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_task_gradelevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='gradeLevel',
            new_name='grade_level',
        ),
    ]
